"""One-shot: resolve bot directory names to Telegram usernames. Delete after use.

This is the only place a bot token is read to produce bots.yml, and it runs on
the machine that can read /usr/local/etc/botkit/*.env. The E2E runner never does
this - that separation is the whole point of bots.yml, and
tests/test_no_token_reads.py is the gate that keeps it.

Reads each token, calls getMe, writes usernames. Tokens are never printed, never
written, never sent anywhere except api.telegram.org. Output is quoted, because
a bare @ is a YAML reserved indicator and would make the file a parse error.

Refuses to write a file of empty usernames: bots.yml with blanks would pass a
"is it committed" check while the runner could never run.

Usage, on the host that owns the bot env files:
    python3 resolve_bots.py --env-dir /usr/local/etc/botkit --out bots.yml
    rm resolve_bots.py
"""

from __future__ import annotations

import argparse
import json
import sys
import urllib.error
import urllib.request
from pathlib import Path

TOKEN_KEYS = ("TELEGRAM_BOT_TOKEN", "BOT_TOKEN")


def read_token(env_file: Path) -> str | None:
    for raw in env_file.read_text().splitlines():
        line = raw.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        key = key.strip()
        if key in TOKEN_KEYS:
            value = value.strip().strip('"').strip("'")
            # A variable reference is not a secret we can use.
            if value and not value.startswith("${"):
                return value
    return None


def get_username(token: str, timeout: int = 10) -> str | None:
    url = f"https://api.telegram.org/bot{token}/getMe"
    try:
        # Fixed https host, not user input, so the S310 band is not enabled here.
        with urllib.request.urlopen(url, timeout=timeout) as resp:
            data = json.loads(resp.read())
    except (urllib.error.URLError, OSError, TimeoutError, json.JSONDecodeError):
        return None
    if not data.get("ok"):
        return None
    return (data.get("result") or {}).get("username")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--env-dir", default="/usr/local/etc/botkit")
    ap.add_argument("--out", default="bots.yml")
    # The env files are named bookingbot.env, while the fleet keys used by
    # scenarios.yml and bots.yml are botkit-bookingbot. Without this the file
    # would resolve nine names that match nothing in the runner.
    ap.add_argument("--prefix", default="botkit-")
    args = ap.parse_args()

    env_dir = Path(args.env_dir)
    if not env_dir.is_dir():
        print(f"not a directory: {env_dir}")
        return 2

    resolved: dict[str, str] = {}
    failed: list[str] = []
    for env_file in sorted(env_dir.glob("*.env")):
        bot = f"{args.prefix}{env_file.stem}"
        token = read_token(env_file)
        if not token:
            failed.append(f"{bot}: no token key in file")
            continue
        username = get_username(token)
        if not username:
            failed.append(f"{bot}: getMe did not return a username")
            continue
        resolved[bot] = username

    if not resolved:
        print("nothing resolved; refusing to write a file of empty usernames")
        for line in failed:
            print(f"  {line}")
        return 1

    header = (
        "# Generated by tools/resolve_bots.py on the machine that can read the bot\n"
        "# tokens, then committed. The E2E runner reads usernames only and cannot\n"
        "# impersonate a bot. The generator is a one-shot tool: delete it after use.\n"
    )
    body = "".join(f'{bot}: "{username}"\n' for bot, username in sorted(resolved.items()))
    Path(args.out).write_text(header + body)

    print(f"wrote {args.out}: {len(resolved)} bot(s)")
    for bot, username in sorted(resolved.items()):
        print(f"  {bot} -> @{username}")
    if failed:
        print("unresolved:")
        for line in failed:
            print(f"  {line}")
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
