server:
  http_listen_address: 127.0.0.1
  grpc_listen_address: 127.0.0.1
  http_listen_port: 3200
  grpc_listen_port: 9096

distributor:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 127.0.0.1:4319
        http:
          endpoint: 127.0.0.1:4320

ingester:
  max_block_duration: 5m
  trace_idle_period: 10s

compactor:
  compaction:
    block_retention: 720h
    compacted_block_retention: 1h

storage:
  trace:
    backend: s3
    s3:
      bucket: tempo
      endpoint: 127.0.0.1:9000
      access_key: ${MINIO_ROOT_USER}
      secret_key: ${MINIO_ROOT_PASSWORD}
      insecure: true
