server:
  http_listen_port: 3200
  grpc_listen_port: 9096

distributor:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4319
        http:
          endpoint: 0.0.0.0:4320

ingester:
  max_block_duration: 5m
  trace_idle_period: 10s

compactor:
  compaction:
    block_retention: 720h
    compacted_block_retention: 1h

storage:
  trace:
    backend: local
    local:
      path: /var/tempo
